///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/battle.aks
/// Generation time: mi., 26 de oct. de 2016 21:22:40
///

/// Song 'pre_music_battle' metadata macros
#define pre_music_battle_address  0x05AF
#define pre_music_battle_size     1530
#define pre_music_battle_end      0x

/// Song 'pre_music_battle' array declaration
extern void pre_music_battle[pre_music_battle_size];
