///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/presentation.aks
/// Generation time: mi., 26 de oct. de 2016 21:22:41
///

/// Song 'pre_music_presentation' metadata macros
#define pre_music_presentation_address  0x0200
#define pre_music_presentation_size     682
#define pre_music_presentation_end      0x

/// Song 'pre_music_presentation' array declaration
extern void pre_music_presentation[pre_music_presentation_size];
